### PR TITLE
eliminate unused dependencies

### PR DESCRIPTION
**Pull request by Humm42**
Over time, some dependencies have been introduced and later eliminated without removing them from Build.PL.

List::MoreUtils was introduced in 911738e335c3 ("Added MoreUtils dep") and List::MoreUtils::XS in 2c14e81e1313 ("Bumped U::C and a few other modules"); neither was used anywhere.

Encode::Locale was introduced by b07014d2efbe ("Looking at #310 more"). Its usage was removed in c0021480df3f ("reverted some locale sets for globbing").

Commit 10c32ef697f3 ("Updating for better NFD/NFC") introduced Unicode::GCString, Encode::EUCJPASCII, Encode::JIS2K, and Encode::HanExtra. While Unicode::GCString is in use, the other three weren't ever used.

PerlIO::utf8_strict, introduced in 9de91b2c2d88 ("Moved to File::Slurper"), was never used either.

Commit d4c27bab2acc ("Simplified extended names") introduced Text::CSV and Text::CSV_XS without using Text::CSV_XS.

The build dependency Config::AutoConf was introduced by d735820cf7df ("Added Config::AutoConf to build deps to catch T::B dependency early"). While it is true that Text::BibTeX requires AutoConf, that is hardly a good reason to list it as dependency of biber--and certainly not without documenting why.

The other build dependency, ExtUtils::LibBuilder, was introduced by 0fa23970034e ("Tidied docs"). It, too, is used by Text::BibTeX. It, too, should not be listed in biber.

This commit does not do anything to dist/.

### CODE REVIEW

**Comment by plk** [comment]
I'm afraid it's not as simple as this. For example, the Encode modules are dynamically loaded depending on what encodings are passed in the `.bcf` and so a comprehensive set of them is needed even if none are explicitly loaded in the source. The dependencies in general are not for `biber` but for `PAR::Packer` and its use of `Module::Scandeps`. Packaging `biber` needs these since the perl is self-contained and so some of these dependencies are needed for packaged versions of `biber` which is the usual use-case. When using the source and `biber` as a perl program, some might not be necessary but this is not the usual use-case.

**Comment by Humm42** [comment]
By what are the `Encode` modules loaded? Grepping the source of biber itself yields nothing. If another package does and doesn’t declare them as dependency, I believe it should be documented.

You state that the common case is a biber packed by `PAR::Packer`. While I do disagree, I also think that that doesn’t matter: Even if the common case is a packed biber, that should not be encoded in the `Build.PL`. That file is for the specific case of using `Module::Build` to install the package as a normal Perl package—presumably, the binaries in some `bin` and the modules in some `site_perl`.

If there need be structure to support packing, it should not constrain the standard (even if less common) case of simply installing the package. If a special `Build.PL` is useful for packing the package, it shouldn’t be named `Build.PL` in the root of the repository.

Now, to the common case: I believe the common case is not, as you believe, a pre-packed biber, but a simple installation. I believe the common case is installing biber from a package repository. For those, packing biber would only do harm.

The case where packing biber would provide benefit (i.e., Windows) is a corner case. On other systems where biber is not in the repositories, actually using the `Build.PL` is beneficial and not hard.

Even if you disagree on my points, it would do good to have a `Build.PL` not constrained by (i.e., with less dependencies than needed with) `Packer`.

**Comment by plk** [comment]
For encoding, it bottoms out in `slurp_switchr()` in `Utils.pm`. The encoding comes from various `biblatex` and `biber` options which are all documented.

The vast majority of users use packed `biber` distributed with TexLive or MikTeX and don't know anything about Perl, nor that it's written in Perl. This is why not much attention has been paid to `Build.PL` since installing a few more packages isn't usually an issue for those who are using the unpacked source tree.

**Comment by Humm42** [comment]
Even if the vast majority of users use a packed biber, attention should be paid to `Build.PL` for those packaging biber. That’s what I am doing right now—creating a package (“port”) for OpenBSD. I would appreciate help in determining the set of dependencies. One form of such help could be having a `Build.PL` plainly stating what packages are required for biber without `Module::Packer`. And with that, I am trying to help right now. Please help me with helping with that.

I suggest you review which dependencies that I said are not needed are needed for the `Module::Packer` case and which ones are needed anyway, then put comments on those that are needed anyway but not greppable.

**Comment by vadimkantorov** [comment]
A very related issue: https://github.com/plk/biber/issues/338

I tried to collect there a full list of dependencies. Removing them or making them optional (also, making disablable internet access and external process launches) would help a lot towards having a static perl build without going via PAR. Building biber then for WebAssembly is also viable.

**Pull request closed without merging**
