### PR TITLE
Build 32bit Linux binary on CentOS 6

### PR DESCRIPTION
**Pull request by moewew**

### CODE REVIEW

**Comment by moewew** [comment]
The binary can be downloaded at https://drive.google.com/file/d/1WjdHVIEEzIW69A3tgB_LozYbhhJvwu4j/

**Comment by plk** [comment]
I should add you to the biber binary communications - can you upload to the linux folder:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/

Let me know if you don't have permissions.

**Comment by moewew** [comment]
I'm https://sourceforge.net/u/moewe/profile/ on SF. I don't think I can upload anything at the moment.

**Comment by plk** [comment]
I added you as a developer for biber - you should be able to upload now?

**Comment by moewew** [comment]
I can't seem to find a way to upload files via the web interface. https://sourceforge.net/p/forge/documentation/Files/ suggests this should work if I'm a *release technican*?

**Comment by plk** [comment]
There should be an upload button - you may have to log out/in again to get the permissions?

**Comment by moewew** [comment]
Mhh, I still can't see a button. I'll pack up the archive and put it up to Google Drive. Maybe if I find the time later I'll see if I can use rsync or something else to upload the file bypassing the web interface.

**Comment by plk** [comment]
Hmm, I have made you admin - does that help? I wonder if SF have changed some things again ...

**Comment by krumeich** [comment]
I can't see the upload button either. I think we had this problem before when I did my first uploads.

**Comment by plk** [comment]
Ah, the SF have changed the permisions, I'll have a look

**Comment by plk** [comment]
I've made people admin for now.

**Comment by moewew** [comment]
I can now see the button when I'm logged in via my Windows machine. But I can't see the button when I'm on SF via my Virtual machine. This is odd...

**Comment by krumeich** [comment]
Thanks, I can see the upload button now.

**Comment by plk** [comment]
Probably just SF syncing across its server farm.

**Comment by moewew** [comment]
Anyhow, it's uploading now. Thank you.

**Comment by krumeich** [comment]
Same for me. Uploading via scp. It's incredibly slow, though.

**Comment by plk** [comment]
Yes, I think SF are doing some work - uploading has been amazingly slow today

**Comment by moewew** [comment]
@plk Can you merge this PR so that the 32-bit linux builds are again in `dist`, please?

**Comment by plk** [comment]
Certaintly - I was going to ask about this but I missed this PR - would it be possible to re-create it to merge into the branch now that master is frozen at v2.13?

**Pull request closed without merging**
