### PR TITLE
utf8 underway

### PR DESCRIPTION
**Pull request by ambs**
Hi
Not a real PR yet. Still failing tests, but maybe you can help me debug some.

This was the evolution yesterday night:

```
# Failed 7/43 test programs. 20/964 subtests failed.
# Failed 7/43 test programs. 20/964 subtests failed.
# Failed 7/43 test programs. 21/1031 subtests failed.
# Failed 7/43 test programs. 18/1031 subtests failed.
# Failed 7/43 test programs. 18/1031 subtests failed.
# Failed 7/43 test programs. 16/1031 subtests failed.
# Failed 7/43 test programs. 15/1031 subtests failed.
```

Cheers

### CODE REVIEW

**Comment by ambs** [comment]
`````
Failed 6/43 test programs. 14/1031 subtests failed.
`````

**Comment by ambs** [comment]
``````
Failed 5/43 test programs. 13/1031 subtests failed.
``````

**Comment by ambs** [comment]
t/encoding.t is failing to read a latin9 file, probably because now Text::BibTeX returns everything utf8-ized. Not sure how Biber was doing this, but can't we slurp the latin9 file, encode it as utf8, and send it bck to Text::BibTeX?

**Comment by plk** [comment]
Hmm, that is a problem - the module needs to respect the encoding of the .bib and return things in that encoding. This is the issue with trying to do all this - either you leave it as bytes, which doesn't break anything, or you need to be able to pass options with the encoding to open with. This is what biber allows - users can pass in encoding names for input data and biber will open with that encoding, then it recodes to NFD UTF-8 internally to do everything and then back to whatever encoding the user wants on output.

**Comment by plk** [comment]
Since the module always reads just bytes, there could be an "output encoding" option to pass to `decode()` instead of just the `decode_utf8` alias? That would be fairly easy.

**Comment by plk** [comment]
I would also, thinking about it, make an option for NFD vs NFC since the module could be considered as either "internal" to a perl program and therefore needed NFD or it could be used as an external boundary to output data in which case NFC would be better. NFD probably would be the default since it's a module mean to be used by a perl program which would be using NFD internally,

**Comment by ambs** [comment]
Agreed, I think. Will look a little to Text::BibTeX again.

**Comment by ambs** [comment]
With "new" Text::BibTeX:

````
Failed 5/43 test programs. 13/1031 subtests failed.
`````
so, so far, so good!

**Comment by ambs** [comment]
````
Failed 5/43 test programs. 12/1031 subtests failed.
````

**Comment by ambs** [comment]
`````
Failed 4/43 test programs. 9/1031 subtests failed.
``````

**Comment by ambs** [comment]
Unfortunately do not have much more ideas on how to fix remaining tests :(

**Comment by ambs** [comment]
````
Failed 3/43 test programs. 8/1017 subtests failed.
`````

**Comment by ambs** [comment]
``````
Failed 1/43 test programs. 1/1031 subtests failed.
``````

**Comment by ambs** [comment]
everything passing. There is a little confusion on Biber code, given it seems now some strings are in NFC others in NFD. I have no clue on what that means, but probably if you can get everything in NFC it gets easier. uff...

Your non-unicode handling is done by biber, not Text::BibTeX. So probably we can just make everything utf by default on Text::BibTeX. That would be my choice. Users using older encodings, nd trying to use Text::BibTeX directly will be forced to use UTF8. But I do not think that to be a big assle.

**Comment by plk** [comment]
I will need some time to look at this but in general, is it now a clean interface in T::B which always returns UTF-8 from all API interfaces? If some things return UTF-8 and some bytes, it will be confusing I think. Can we pass an option to tell it to return bytes or UTF-8 and NFC/NFD? I think that would help backwards compat - I am in the middle of large biber changes and so I'd probably keep it on bytes and then do incremental testing.

**Comment by ambs** [comment]
Yes, everything returns UTF-8. I just didn't add the utf code for the entry type nd field names as they usually are just ascii, but I will add that code there too.

Have UTF-8 or bytes, yeah, probably easy to do. In fact, that would be kind of my first code. Will give details when I have them.

Cheers

**Comment by ambs** [comment]
(will keep this branch accurate with current Text::BibTeX git, so it then can be used as reference)

**Comment by plk** [comment]
This was fixed some time ago now ...

**Pull request closed without merging**
